#! /bin/bash
#
# Startup Script for CSS Archive Engine
#
# chkconfig: - 92 8
# description: Starts and stops CSS Archive Engine
#

#+======================================================================
# $HeadURL: https://svnpub.iter.org/codac/iter/codac/dev/units/m-css-archive/trunk/org.csstudio.archive.engine/css-archive-engine $
# $Id: css-archive-engine 28074 2012-05-27 16:29:10Z zagara $
#
# Project       : CODAC Core System
#
# Description   : Starts and stops CSS Archive Engine
#
# Author(s)     : Cosylab
#
# Copyright (c) : 2010-2014 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

. codacenv

CONFIGURATION=()
VARFILES=()

unset REQUSER
DAEMONS=(/usr/bin/archive-engine)
NAMES=("CSS Archive Engine")
ARGS=("-engine CODAC $(printf "'%s' " "${@:2}")")

. $CODAC_ROOT/bin/services/service-startup
