#!/bin/sh
#
# scan_server  Service-type script to control the scan server
#
# chkconfig: - 80 20
#
# kasemirk@ornl.gov

SCAN_SERVER=/home/css/ScanServer0.1

# Default scan server RMI uses 4810, 4811
# Use 4809 for telnet access
CONSOLE=4809
ARGS="-console $CONSOLE -data $SCAN_SERVER/workspace -consoleLog"
USER=ky9

export JAVA_HOME=/usr/lib/jvm/jre-1.6.0-sun.x86_64


export PATH=$JAVA_HOME:$PATH
unset DISPLAY

function start()
{
	su - $USER -c "nohup $SCAN_SERVER/ScanServer $ARGS >>$SCAN_SERVER/console.log 2>&1 &"
}

function stop()
{
	echo close | nc localhost $CONSOLE
}

case $1 in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
status)
	ps aux | fgrep ScanServer | grep -v fgrep
	;;
telnet)
	telnet localhost $CONSOLE
	;;
*)	echo "Usage: $0 {start|stop|restart|status|telnet}"
        exit 2
esac
