<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<databrowser>
    <title>
        <text>Beauty Plot</text>
        <color>
            <red>0</red>
            <green>0</green>
            <blue>255</blue>
        </color>
        <font>1|Sans|12.0|1|GTK|1|</font>
    </title>
    <graph_settings>
        <show_title>true</show_title>
        <show_legend>true</show_legend>
        <show_plot_area_border>false</show_plot_area_border>
        <transparent>false</transparent>
    </graph_settings>
    <scroll>true</scroll>
    <update_period>3.0</update_period>
    <start>-1 hours 0.0 seconds</start>
    <end>now</end>
    <time_axis>
        <axis>
            <name>Time</name>
            <font>1|Sans|10.0|1|GTK|1|</font>
            <scale_font>1|Sans|10.0|0|GTK|1|</scale_font>
            <color>
                <red>0</red>
                <green>0</green>
                <blue>0</blue>
            </color>
            <min>1.36628927793E12</min>
            <max>1.36629287793E12</max>
            <log_scale>false</log_scale>
            <autoscale>true</autoscale>
            <visible>true</visible>
            <grid_line>
                <show_grid_line>false</show_grid_line>
                <dash_grid_line>true</dash_grid_line>
                <color>
                    <red>200</red>
                    <green>200</green>
                    <blue>200</blue>
                </color>
            </grid_line>
            <format>
                <auto_format>true</auto_format>
                <time_format>true</time_format>
                <format_pattern>HH:mm</format_pattern>
            </format>
        </axis>
    </time_axis>
    <background>
        <red>255</red>
        <green>255</green>
        <blue>255</blue>
    </background>
    <archive_rescale>NONE</archive_rescale>
    <axes>
        <axis>
            <name>TEST-BTY0:AIn</name>
            <font>1|Sans|10.0|1|GTK|1|</font>
            <scale_font>1|Sans|10.0|0|GTK|1|</scale_font>
            <color>
                <red>21</red>
                <green>21</green>
                <blue>196</blue>
            </color>
            <min>0.0</min>
            <max>108.49089341573206</max>
            <log_scale>false</log_scale>
            <autoscale>true</autoscale>
            <visible>true</visible>
            <grid_line>
                <show_grid_line>false</show_grid_line>
                <dash_grid_line>true</dash_grid_line>
                <color>
                    <red>200</red>
                    <green>200</green>
                    <blue>200</blue>
                </color>
            </grid_line>
            <format>
                <auto_format>true</auto_format>
                <time_format>false</time_format>
                <format_pattern>############.##</format_pattern>
            </format>
        </axis>
        <axis>
            <name>TEST-BTY0:RAMP1</name>
            <font>1|Sans|10.0|1|GTK|1|</font>
            <scale_font>1|Sans|10.0|0|GTK|1|</scale_font>
            <color>
                <red>139</red>
                <green>105</green>
                <blue>20</blue>
            </color>
            <min>-1.0000321507591365</min>
            <max>100.0</max>
            <log_scale>false</log_scale>
            <autoscale>true</autoscale>
            <visible>true</visible>
            <grid_line>
                <show_grid_line>false</show_grid_line>
                <dash_grid_line>true</dash_grid_line>
                <color>
                    <red>200</red>
                    <green>200</green>
                    <blue>200</blue>
                </color>
            </grid_line>
            <format>
                <auto_format>true</auto_format>
                <time_format>false</time_format>
                <format_pattern>############.##</format_pattern>
            </format>
        </axis>
        <axis>
            <name>TEST-BTY0:RAMP2</name>
            <font>1|Sans|10.0|1|GTK|1|</font>
            <scale_font>1|Sans|10.0|0|GTK|1|</scale_font>
            <color>
                <red>160</red>
                <green>32</green>
                <blue>240</blue>
            </color>
            <min>-1.0000321507591365</min>
            <max>100.0</max>
            <log_scale>false</log_scale>
            <autoscale>true</autoscale>
            <visible>true</visible>
            <grid_line>
                <show_grid_line>false</show_grid_line>
                <dash_grid_line>true</dash_grid_line>
                <color>
                    <red>200</red>
                    <green>200</green>
                    <blue>200</blue>
                </color>
            </grid_line>
            <format>
                <auto_format>true</auto_format>
                <time_format>false</time_format>
                <format_pattern>############.##</format_pattern>
            </format>
        </axis>
    </axes>
    <annotations>
    </annotations>
    <pvlist>
        <pv>
            <name>TEST-BTY0:AI1</name>
            <display_name>TEST-BTY0:AI1</display_name>
            <visible>true</visible>
            <axis>0</axis>
            <linewidth>2</linewidth>
            <color>
                <red>21</red>
                <green>21</green>
                <blue>196</blue>
            </color>
            <trace_type>AREA</trace_type>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>rdb</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <name>TEST-BTY0:AI2</name>
            <display_name>TEST-BTY0:AI2</display_name>
            <visible>true</visible>
            <axis>0</axis>
            <linewidth>2</linewidth>
            <color>
                <red>242</red>
                <green>26</green>
                <blue>26</blue>
            </color>
            <trace_type>AREA</trace_type>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>rdb</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <name>TEST-BTY0:AI3</name>
            <display_name>TEST-BTY0:AI3</display_name>
            <visible>true</visible>
            <axis>0</axis>
            <linewidth>2</linewidth>
            <color>
                <red>66</red>
                <green>177</green>
                <blue>66</blue>
            </color>
            <trace_type>AREA</trace_type>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>rdb</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <name>TEST-BTY0:RAMP1</name>
            <display_name>TEST-BTY0:RAMP1</display_name>
            <visible>true</visible>
            <axis>1</axis>
            <linewidth>2</linewidth>
            <color>
                <red>139</red>
                <green>105</green>
                <blue>20</blue>
            </color>
            <trace_type>AREA</trace_type>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>rdb</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <name>TEST-BTY0:RAMP2</name>
            <display_name>TEST-BTY0:RAMP2</display_name>
            <visible>true</visible>
            <axis>2</axis>
            <linewidth>2</linewidth>
            <color>
                <red>128</red>
                <green>0</green>
                <blue>255</blue>
            </color>
            <trace_type>AREA</trace_type>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>rdb</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
    </pvlist>
</databrowser>