
/* 
 * Copyright (c) 2006 Stiftung Deutsches Elektronen-Synchrotron, 
 * Member of the Helmholtz Association, (DESY), HAMBURG, GERMANY.
 *
 * THIS SOFTWARE IS PROVIDED UNDER THIS LICENSE ON AN "../AS IS" BASIS. 
 * WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED 
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE AND 
 * NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
 * THE USE OR OTHER DEALINGS IN THE SOFTWARE. SHOULD THE SOFTWARE PROVE DEFECTIVE 
 * IN ANY RESPECT, THE USER ASSUMES THE COST OF ANY NECESSARY SERVICING, REPAIR OR 
 * CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. 
 * NO USE OF ANY SOFTWARE IS AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.
 * DESY HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, 
 * OR MODIFICATIONS.
 * THE FULL LICENSE SPECIFYING FOR THE SOFTWARE THE REDISTRIBUTION, MODIFICATION, 
 * USAGE AND OTHER RIGHTS AND OBLIGATIONS IS INCLUDED WITH THE DISTRIBUTION OF THIS 
 * PROJECT IN THE FILE LICENSE.HTML. IF THE LICENSE IS NOT INCLUDED YOU MAY FIND A COPY 
 * AT HTTP://WWW.DESY.DE/LEGAL/LICENSE.HTM
 */

package org.csstudio.utility.screenshot.desy.preference;

import org.csstudio.utility.screenshot.desy.DestinationPlugin;
import org.eclipse.core.runtime.preferences.AbstractPreferenceInitializer;
import org.eclipse.jface.preference.IPreferenceStore;

public class DestinationPreferenceInitializer extends AbstractPreferenceInitializer
{

    @Override
    public void initializeDefaultPreferences()
    {
        IPreferenceStore store = DestinationPlugin.getDefault().getPreferenceStore();
        
        store.setDefault(DestinationPreferenceConstants.MAIL_ADDRESS_SENDER, "css_user@desy.de");
        store.setDefault(DestinationPreferenceConstants.MAIL_SERVER, "smtp.desy.de");
        store.setDefault(DestinationPreferenceConstants.LOGBOOK_NAMES, "MKS-2;KRYO;CTA;CMTB;MKK;MKS-1;MKS-3;MKS-4;MVA;MHF;MST;MDI;MHF-SL;HASYLAB;D3;D5;EVENT;IT-NEWS;HERA;eLog;ALARM-KRYO;ALARM-D3;ALARM-SMS;ALARM-MKK;ALARM-WASS;ALARM-KLIM;IOC-Log;IOC-PutLog;TTFX;HERAX;PETRAX;DORISX;DESY2X;DESY3X;LINAC2X;LINAC3X;MySql;HERA-X;OP-LOG;CMLOG;TTF;ALARM;TEST;CMTB"); 
        store.setDefault(DestinationPreferenceConstants.GROUP_NAMES, "D3;Guest;IHEP-CHINA;IHEP-RUSS;IPP;IT;MDI;MHF-SL;MKI;MKK;MKS;MKS-1;MKS-2;MKS-3;MKS-4;MPY;MVP;MVA;Test"); 
    }
}
