--
-- Table structure for table `engine_status`
--

DROP TABLE IF EXISTS `engine_status`;
CREATE TABLE `engine_status` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `engine_id` int(10) unsigned NOT NULL,
  `status` enum('ON','OFF') NOT NULL,
  `time` datetime NOT NULL,
  `info` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`,`time`,`engine_id`)
) ENGINE=InnoDB AUTO_INCREMENT=288 DEFAULT CHARSET=latin1
PARTITION BY RANGE (TO_DAYS(time))
SUBPARTITION BY HASH (engine_id)
SUBPARTITIONS 40
(PARTITION p0 VALUES LESS THAN (734442) ENGINE = InnoDB,
 PARTITION p1 VALUES LESS THAN (734472) ENGINE = InnoDB,
 PARTITION p2 VALUES LESS THAN (734503) ENGINE = InnoDB,
 PARTITION p3 VALUES LESS THAN (734534) ENGINE = InnoDB,
 PARTITION p4 VALUES LESS THAN (734562) ENGINE = InnoDB,
 PARTITION p5 VALUES LESS THAN (734593) ENGINE = InnoDB,
 PARTITION p6 VALUES LESS THAN (734623) ENGINE = InnoDB,
 PARTITION p7 VALUES LESS THAN (734654) ENGINE = InnoDB,
 PARTITION p8 VALUES LESS THAN (734684) ENGINE = InnoDB,
 PARTITION p9 VALUES LESS THAN (734715) ENGINE = InnoDB,
 PARTITION p10 VALUES LESS THAN (734746) ENGINE = InnoDB,
 PARTITION p11 VALUES LESS THAN (734776) ENGINE = InnoDB,
 PARTITION p12 VALUES LESS THAN (734807) ENGINE = InnoDB,
 PARTITION p13 VALUES LESS THAN (734837) ENGINE = InnoDB,
 PARTITION p14 VALUES LESS THAN (734868) ENGINE = InnoDB,
 PARTITION p15 VALUES LESS THAN (734899) ENGINE = InnoDB,
 PARTITION p16 VALUES LESS THAN (734928) ENGINE = InnoDB,
 PARTITION p17 VALUES LESS THAN (734959) ENGINE = InnoDB,
 PARTITION p18 VALUES LESS THAN (734989) ENGINE = InnoDB,
 PARTITION p19 VALUES LESS THAN (735020) ENGINE = InnoDB,
 PARTITION p20 VALUES LESS THAN (735050) ENGINE = InnoDB,
 PARTITION p21 VALUES LESS THAN (735081) ENGINE = InnoDB,
 PARTITION p22 VALUES LESS THAN (735112) ENGINE = InnoDB,
 PARTITION p23 VALUES LESS THAN (735142) ENGINE = InnoDB,
 PARTITION pRest VALUES LESS THAN MAXVALUE ENGINE = InnoDB);
