# whitelist 
language: java

env:  
  global:  
   - DISPLAY=:99.0

sudo: false

dist: cosmic

addons:
  apt:
    packages:
      - openjdk-11-jdk

install: echo 'Skipping mvn install'

before_script:
 - chmod +x travis.sh
 - echo "MAVEN_OPTS='-Xmx2g -Xms1g'" > ~/.mavenrc

script:
 - java -version
 - ./travis.sh 

after_failure:
 - find . -type f -name "*.log" -print0 -exec cat {} \;

