TOP = ..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================


LIBRARY_IOC += stateProgs

stateProgs_SRCS += cueberw.st
stateProgs_SRCS += kbetrieb.st
stateProgs_SRCS += tukreis1.st
stateProgs_SRCS += Adsorber.st
#stateProgs_SRCS += sal_ndk1.st

stateProgs_LIBS += seq pv


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

