CREATE SEQUENCE AMS_FILTER_ID MINVALUE 1 INCREMENT BY 1 START WITH 1 NO CYCLE ;
CREATE SEQUENCE AMS_FILTERACTION_ID MINVALUE 1 INCREMENT BY 1 START WITH 1 NO CYCLE ;
CREATE SEQUENCE AMS_FILTERCONDITION_ID MINVALUE 1 INCREMENT BY 1 START WITH 1 NO CYCLE ;
CREATE SEQUENCE AMS_GROUPS_ID MINVALUE 1 INCREMENT BY 1 START WITH 1 NO CYCLE ;
CREATE SEQUENCE AMS_TOPIC_ID MINVALUE 1 INCREMENT BY 1 START WITH 1 NO CYCLE ;
CREATE SEQUENCE AMS_USER_ID MINVALUE 0 INCREMENT BY 1 START WITH 1 NO CYCLE ;
CREATE SEQUENCE AMS_USERGROUP_ID MINVALUE 1 INCREMENT BY 1 START WITH 1 NO CYCLE ;
