/*******************************************************************************
 * Copyright (c) 2010-2016 ITER Organization.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 ******************************************************************************/
package org.csstudio.utility.batik;

import org.eclipse.swt.graphics.Image;

/**
 * Listener of {@link SVGHandler} to be notified of images generated by the {@link UpdateManager} i.e. when an animated
 * SVG file with animation started is specified.
 *
 * @author Fred Arnaud (Sopra Steria Group) - ITER
 */
public interface SVGHandlerListener {

    /**
     * In case of animated SVG, notifies when a new {@link Image} is available. {@link SVGHandler} is responsible of
     * images disposal. For practical reason, this method is invoked in the UI thread.
     *
     * @param image, new image to display.
     */
    public void newImage(Image image);
}
