#! /bin/bash
#
# Startup Script for CSS Alarm Notifier
#
# chkconfig: - 93 7
# description: Starts and stops CSS Alarm Notifier
#

#+======================================================================
# $HeadURL$
# $Id$
#
# Project       : CODAC Core System
#
# Description   : Starts and stops CSS Alarm Notifier
#
# Author(s)     : Cosylab
#
# Copyright (c) : 2010-2014 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

. codacenv

CONFIGURATION=()
VARFILES=()

unset REQUSER
DAEMONS=(/usr/bin/alarm-notifier)
NAMES=("CSS Alarm Notifier")
ARGS=("$([ $# -gt 1 ] && printf "'%s' " "${@:2}")")

. $CODAC_ROOT/bin/services/service-startup
