CREATE CACHED TABLE AMS_History
(
	iHistoryID		INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	tTimeNew		BIGINT,
	cType			VARCHAR(16),
	cMsgHost		VARCHAR(64),
	cMsgProc		VARCHAR(64),
	cMsgName		VARCHAR(64),
	cMsgEventTime	VARCHAR(32),
	cDescription	VARCHAR(512),
	cActionType		VARCHAR(16),	
	iGroupRef		INT,
	cGroupName		VARCHAR(64),
	iReceiverPos	INT,
	iUserRef 		INT,
	cUserName 		VARCHAR(128),
	cDestType		VARCHAR(16),	
	cDestAdress		VARCHAR(128),
	PRIMARY KEY(iHistoryID)
);
