#!/bin/sh
#
# Scipt to path product ZIPs created by headless built
# Args: original-zip-name  product-name  final-zip-name
#
# Kay Kasemir

cd $BUILDDIR
orig=$1
product=$2
final=$3
    
# Unzip the file generated by headless build
unzip -q $orig
  
# Enable dropins directory
# In configuration/org.eclipse.equinox.simpleconfigurator/bundles.info,
# the org.eclipse.equinox.p2.reconciler.dropins must be set to
# start automatically.
# Unclear how to do that in p2.inf, so using perl
perl -p -i -e 's/(org\.eclipse\.equinox\.p2\.reconciler\.dropins,.+),false/\1,true/;' $product/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info    

# Create new ZIP
rm -f $final
zip -qr $final $product
    
# Cleanup
rm -rf $product
# rm $orig

echo Created $final
