#!/bin/sh
#
# Scipt to path product ZIPs created by headless built
# Args: original-zip-name  product-name executable final-zip-name
#
# Kay Kasemir

orig=$1
product=$2
exe=$3
final=$4
    
# Unzip the file generated by headless build
unzip -q $orig
    
# With a headless build in 3.5, the OS X and Linux launchers were not
# marked executable. https://bugs.eclipse.org/bugs/show_bug.cgi?id=260844 ?
# With 3.6, this seems no longer necessary, but it can't hurt, either.
chmod +x $product/$exe

# Create dropins directory
# Done via p2.inf, but can't hurt to assert it's there, either
mkdir -p $product/dropins
    
# Enable dropins directory
# In configuration/org.eclipse.equinox.simpleconfigurator/bundles.info,
# the org.eclipse.equinox.p2.reconciler.dropins must be set to
# start automatically.
# Unclear how to do that in p2.inf, so using perl
perl -p -i -e 's/(org\.eclipse\.equinox\.p2\.reconciler\.dropins,.+),false/\1,true/;' $product/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info    


# * Remove readme/readme_eclipse.html 
# Eclipse 3.6 started to create this directory in the product.
rm -rf $product/readme

# Create new ZIP
rm -f $final
zip -qr $final $product
    
# Cleanup
rm -rf $product
rm $orig

echo Created $final
