/*
 * Copyright (c) 2011 Stiftung Deutsches Elektronen-Synchrotron,
 * Member of the Helmholtz Association, (DESY), HAMBURG, GERMANY.
 *
 * THIS SOFTWARE IS PROVIDED UNDER THIS LICENSE ON AN "../AS IS" BASIS.
 * WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 * THE USE OR OTHER DEALINGS IN THE SOFTWARE. SHOULD THE SOFTWARE PROVE DEFECTIVE
 * IN ANY RESPECT, THE USER ASSUMES THE COST OF ANY NECESSARY SERVICING, REPAIR OR
 * CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE.
 * NO USE OF ANY SOFTWARE IS AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.
 * DESY HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS,
 * OR MODIFICATIONS.
 * THE FULL LICENSE SPECIFYING FOR THE SOFTWARE THE REDISTRIBUTION, MODIFICATION,
 * USAGE AND OTHER RIGHTS AND OBLIGATIONS IS INCLUDED WITH THE DISTRIBUTION OF THIS
 * PROJECT IN THE FILE LICENSE.HTML. IF THE LICENSE IS NOT INCLUDED YOU MAY FIND A COPY
 * AT HTTP://WWW.DESY.DE/LEGAL/LICENSE.HTM
 */
package org.csstudio.domain.common.softioc;

import javax.annotation.Nonnull;

/**
 * TODO (hrickens) :
 *
 * @author hrickens
 * @since 25.11.2011
 */
public enum DBR {

    DBR_AUTO(-1),
    DBR_STRING(0),
    DBR_STS_FLOAT(9),
    DBR_TIME_LONG(19),
    DBR_CTRL_SHORT(29),
    DBR_INT(1),
    DBR_STS_ENUM(10),
    DBR_TIME_DOUBLE(20),
    DBR_CTRL_INT(29),
    DBR_SHORT(1),
    DBR_STS_CHAR(11),
    DBR_GR_STRING(21),
    DBR_CTRL_FLOAT(30),
    DBR_FLOAT(2),
    DBR_STS_LONG(12),
    DBR_GR_SHORT(22),
    DBR_CTRL_ENUM(31),
    DBR_ENUM(3),
    DBR_STS_DOUBLE(13),
    DBR_GR_INT(22),
    DBR_CTRL_CHAR(32),
    DBR_CHAR(4),
    DBR_TIME_STRING(14),
    DBR_GR_FLOAT(23),
    DBR_CTRL_LONG(33),
    DBR_LONG(5),
    DBR_TIME_INT(15),
    DBR_GR_ENUM(24),
    DBR_CTRL_DOUBLE(34),
    DBR_DOUBLE(6),
    DBR_TIME_SHORT(15),
    DBR_GR_CHAR(25),
    DBR_STSACK_STRING(37),
    DBR_STS_STRING(7),
    DBR_TIME_FLOAT(16),
    DBR_GR_LONG(26),
    DBR_CLASS_NAME(38),
    DBR_STS_SHORT(8),
    DBR_TIME_ENUM(17),
    DBR_GR_DOUBLE(27),
    DBR_STS_INT(8),
    DBR_TIME_CHAR(18),
    DBR_CTRL_STRING(28);

    /**
     * The index of his enum.
     */
    private int _index;

    private DBR(final int index) {
        _index = index;
    }

    @Nonnull
    public String getAsOptionString() {
        if (_index>=0) {
            return "-d "+_index;
        }
        return "";
    }

}
