/**
 * Copyright (C) 2010-12 Brookhaven National Laboratory
 * All rights reserved. Use is subject to license terms.
 */
package org.epics.pvmanager.expression;

import org.epics.pvmanager.extra.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import org.epics.pvmanager.ReadRecipe;
import org.epics.pvmanager.DataSource;
import org.epics.pvmanager.expression.DesiredRateExpression;
import org.epics.pvmanager.expression.DesiredRateExpressionImpl;
import org.epics.pvmanager.ExceptionHandler;
import org.epics.pvmanager.PVManager;
import org.epics.pvmanager.PVReaderDirector;
import org.epics.pvmanager.QueueCollector;
import org.epics.pvmanager.ReadRecipeBuilder;
import org.epics.pvmanager.expression.DesiredRateExpressionListImpl;

/**
 * A expression that returns the result of a dynamically managed group.
 * Once the group is created, any {@link DesiredRateExpression} can be
 * added dynamically. The exceptions eventually generated by those
 * expressions can be obtained through {@link #lastExceptions() }.
 *
 * @author carcassi
 */
public class ReadWriteMap<R, W> extends DesiredRateReadWriteExpressionImpl<Map<String, R>, Map<String, W>> {

    private final Object lock = new Object();
    private final Map<String, DesiredRateExpression<R>> expressions = new HashMap<>();
    private PVReaderDirector<?> director;

    /**
     * Creates a new group.
     */
    public ReadWriteMap() {
        super(new ReadMap<R>(), new WriteMap<W>());
    }
    
    private ReadMap<R> getReadMap() {
        return (ReadMap<R>) getDesiredRateExpressionImpl();
    }
    
    private WriteMap<W> getWriteMap() {
        return (WriteMap<W>) getWriteExpressionImpl();
    }

    /**
     * Removes all the expressions currently in the group.
     * 
     * @return this
     */
    public ReadWriteMap<R, W> clear() {
        getReadMap().clear();
        getWriteMap().clear();
        return this;
    }

    /**
     * Returns the number of expressions in the group.
     * 
     * @return number of expressions in the group
     */
    public int size() {
        return getReadMap().size();
    }

    /**
     * Adds the expression at the end.
     * 
     * @param expression the expression to be added
     * @return this
     */
    public ReadWriteMap<R, W> add(DesiredRateReadWriteExpression<R, W> expression) {
        getReadMap().add(expression);
        getWriteMap().add(expression);
        return this;
    }
    
    public ReadWriteMap<R, W> add(DesiredRateReadWriteExpressionList<R, W> expressions) {
        getReadMap().add(expressions);
        getWriteMap().add(expressions);
        return this;
    }

    /**
     * Removes the expression at the given location.
     * 
     * @param index the position to remove
     * @return this
     */
    public ReadWriteMap<R, W> remove(String name) {
        getReadMap().remove(name);
        getWriteMap().remove(name);
        return this;
    }
    
    public ReadWriteMap<R, W> remove(List<String> names) {
        getReadMap().remove(names);
        getWriteMap().remove(names);
        return this;
    }
    
}
