~/EngineConfigImport/EngineConfigImport -replace_engine -port 4501 -engine iocs      -config iocHealth-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4502 -engine llrf      -config llrf-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4503 -engine hprf      -config hprf-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4504 -engine refline   -config refline-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4505 -engine pps       -config pps-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4506 -engine mps       -config mps-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4507 -engine rccs      -config rccs-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4508 -engine ps        -config ps-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4509 -engine chmk      -config chmk-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4510 -engine timing    -config tim-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4511 -engine vacuum    -config vac-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4512 -engine blm       -config blm-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4513 -engine cryo20    -config ioc20-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4514 -engine cryo30    -config ioc30-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4515 -engine cryo40    -config ioc40-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4516 -engine cryo50-55 -config iocs50-55-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4517 -engine cryo56-57 -config iocs56-57-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4518 -engine cryo-soft -config soft-iocs-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4519 -engine fe-ioc1   -config ctl-ioc1-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4520 -engine fe-ioc2   -config ctl-ioc2-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4521 -engine fe-ioc3   -config ctl-ioc3-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4522 -engine cf-cc     -config cfcc-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4523 -engine cf-kl     -config kl-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4524 -engine cf-rn     -config rn-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4525 -engine cf-ta     -config ta-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4526 -engine tgt-loops -config loops-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4527 -engine tgt-rid   -config rid-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4528 -engine tgt-mcb   -config mcb-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4529 -engine tgt-shut  -config shut-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4530 -engine tgt-h2    -config h2.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4531 -engine ldmp      -config ldmp-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4532 -engine scraper   -config scraper-group.xml
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4533 -engine pwr_mon   -config pwrMon-group.xml 
~/EngineConfigImport/EngineConfigImport -replace_engine -port 4534 -engine cec       -config cec-group.xml

